### ISSUE TITLE
Dataset unvollständig beim XML-Export

### ISSUE THREAD

**Issue by wbrakowski** [AndreasRascher/MiniReportInspector#1]
Moin Andreas,
ich habe heute mal versucht deinen Mini Report Inspector für einen Verkaufslieferschein (R208) zu benutzen. Das generierte XML-Dataset enthält leider nicht alle Daten. Die Informationen aus den Zeilen sind nicht im Dataset enthalten.

**Comment by AndreasRascher** [comment]
Hallo Waldemar,
ich denke ich konnte das Problem finden und lösen.
